package com.agriinsight.backend.identity.domain;

public enum Permission {
    IDENTITY_USER_MANAGE,
    IDENTITY_ROLE_MANAGE,
    FARM_READ,
    FARM_MANAGE,
    FARM_ASSIGNMENT_MANAGE,
    SEASON_READ,
    SEASON_MANAGE,
    WORKFORCE_MANAGE,
    WORKFORCE_PICKER_READ,
    ACTIVITY_READ,
    ACTIVITY_MANAGE,
    ACTIVITY_LOG_APPEND,
    HARVEST_READ,
    HARVEST_MANAGE,
    INVENTORY_READ,
    INVENTORY_MANAGE,
    INVENTORY_ASSIGNMENT_MANAGE,
    COST_READ,
    COST_MANAGE
}
